### ISSUE TITLE
Server not accessible when account has not been activated by user

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#102]
It happens that user signs up and tries to use Mergin directly in QGIS without activating their accounts.
The error message they get is same as #70 

The error message should be different and should inform users that they need to click on the email to activate their accounts.

**Comment by varmar05** [comment]
let's leave this one open until we upgrade production server

**Comment by varmar05** [comment]
closing now since server has been upgraded (2020.2)
