### ISSUE TITLE
When "Configure" the plugin, it should validate credential

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#112]
When user enters the credential in the Configure window and presses OK, it should validate with the website to see if the credentials are valid.

Currently, user can press OK with wrong credential and encrypted error messages appears in the plugin:
![image](https://user-images.githubusercontent.com/2649047/73829194-7cd5bd80-47fa-11ea-9f91-6dc285e0d58d.png)

Alternatively, it should show a proper error message (invalid username or password) as one might want to use the plugin to Explore the public projects only.

**Comment by varmar05** [comment]
the error message has just been fixed with https://github.com/lutraconsulting/qgis-mergin-plugin/pull/109 to "invalid username ..."
