### ISSUE TITLE
Corrupting data after download

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#115]
There are two separate issues:
1- The plugin fails to download a large file and in the process, it corrupts the file
2- After that, it prompts the user that the download has been completed successfully, instead of warning user about he unsuccessful download.

The example project is sk2 on dev.dev instance.

**Comment by varmar05** [comment]
related to https://github.com/lutraconsulting/mergin-py-client/issues/7
but at this point maybe we can check at least final size of downloaded file
