### ISSUE TITLE
QGIS 3.10.2 doesn't start after configuring plugin and restarting second time

### ISSUE THREAD

**Issue by reginaldc** [lutraconsulting/qgis-mergin-plugin#118]
Hi,

I installed the Mergin plugin in QGIS 3.10.2 on Windows 7.
After restarting the plugin appeared in the browser and I could configure my project and upload and use it. When I close QGIS and open it again I get an error message. The only way to get QGIS to start again is to remove the profile in which I installed the Mergin plugin.
I tried it with a clean profile and only installed Mergin in it => same result.

Regards,

**Comment by saberraz** [comment]
Hi @reginaldc 

Thanks for reporting the issue. Do you get any error message? If so, could you include the error here. It will help us resolve the issue.

Regards
Saber

**Comment by reginaldc** [comment]
I am testing it today but so far I cannot reproduce it. Yesterday it happened 4 times...
I will post the stacktrace if it occurs again,

Regards,

**Comment by reginaldc** [comment]
Hi,

QGIS failed again:


Stack Trace


QEventTransitionPrivate::unregister :
QAbstractItemModel::persistentIndexList :
QAbstractItemModelPrivate::rowsInserted :
QAbstractItemModel::endInsertRows :
QgsBrowserModel::endInsertItems qgsbrowsermodel.cpp:525
QtPrivate::FunctorCall,QtPrivate::List,void,void (__cdecl QgsBrowserModel::*)(void) __ptr64>::call qobjectdefs_impl.h:134
QtPrivate::FunctionPointer::call,void> qobjectdefs_impl.h:168
QtPrivate::QSlotObject,void>::impl qobjectdefs_impl.h:397
QMetaObject::activate :
QgsDataItem::endInsertItems moc_qgsdataitem.cpp:312
QgsDataItem::addChildItem qgsdataitem.cpp:502
QgsDataItem::populate qgsdataitem.cpp:339
QgsDataItem::childrenCreated qgsdataitem.cpp:313
QtPrivate::FunctorCall,QtPrivate::List,void,void (__cdecl QgsDataItem::*)(void) __ptr64>::call qobjectdefs_impl.h:134
QtPrivate::FunctionPointer::call,void> qobjectdefs_impl.h:168
QtPrivate::QSlotObject,void>::impl qobjectdefs_impl.h:397
QMetaObject::activate :
QFutureWatcherBase::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QgsAuthManager::passwordHelperRead qgsauthmanager.cpp:3091
QgsAuthManager::masterPasswordInput qgsauthmanager.cpp:3227
QgsAuthManager::setMasterPassword qgsauthmanager.cpp:504
QgsAuthManager::loadAuthenticationConfig qgsauthmanager.cpp:1211
meth_QgsAuthManager_loadAuthenticationConfig sip_corepart2.cpp:266963
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyTuple_New :
PyObject_FastCallKeywords :
PyObject_FastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_sip :
sipVH__core_57 sip_corepart0.cpp:19836
sipQgsDataItemProvider::createDataItem sip_corepart3.cpp:177631
QgsBrowserModel::addRootItems qgsbrowsermodel.cpp:140
QgsBrowserModel::initialize qgsbrowsermodel.cpp:193
QgsBrowserDockWidget::showEvent qgsbrowserdockwidget.cpp:127
QWidget::event :
QDockWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QgisApp::QgisApp qgisapp.cpp:1370
main main.cpp:1344
WinMain mainwin.cpp:170
__scrt_common_main_seh exe_common.inl:253
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: 032ed312e4
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.0dev
Running against GDAL: 3.1.0dev



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by markvolz** [comment]
I am having the same issue in 3.12.0 (code version cd141490ec) on windows 10 pro. The problem only occurs when the browser panel is active. I have confirmed this via 2 different processes:
1) Start QGIS with the browser panel active it will fail at the splash screen
2) Start QGIS with the browser panel inactive and QGIS will start successfully. When you activate the browser panel QGIS will crash.

I've attached the report details from each process
[path-1.txt](https://github.com/lutraconsulting/qgis-mergin-plugin/files/4398143/path-1.txt)

[path-2.txt](https://github.com/lutraconsulting/qgis-mergin-plugin/files/4398142/path-2.txt)

**Comment by markvolz** [comment]
I have found a workaround:
1) open your current user profile ini file by default it is C:\Users\<username>\AppData\Roaming\QGIS\QGIS3\profiles\default\QGIS\QGIS3.ini
2) go to the Mergin section
3) change saveCredentials=True to saveCredentials=False.

so the issue appears to be with accessing the saved credentials

**Comment by reginaldc** [comment]
Thanks for looking into this.

Regards,


Reginald Carlier
Deskundige GIS
Gemeente Ingelmunster, Oostrozebekestraat 4, 8770 Ingelmunster
T+32 51 33 74 39www.ingelmunster.be
Schrijf je in op onze nieuwsbrief!
Raadpleeg onze disclaimer 
________________________________
Van: markvolz <notifications@github.com>
Verzonden: zondag 29 maart 2020 03:41
Aan: lutraconsulting/qgis-mergin-plugin <qgis-mergin-plugin@noreply.github.com>
CC: Reginald Carlier <Reginald.Carlier@ingelmunster.be>; Mention <mention@noreply.github.com>
Onderwerp: Re: [lutraconsulting/qgis-mergin-plugin] QGIS 3.10.2 doesn't start after configuring plugin and restarting second time (#118)


I have found a workaround:

  1.  open your current user profile ini file by default it is C:\Users<username>\AppData\Roaming\QGIS\QGIS3\profiles\default\QGIS\QGIS3.ini
  2.  go to the Mergin section
  3.  change saveCredentials=True to saveCredentials=False.

so the issue appears to be with accessing the saved credentials

**Comment by saberraz** [comment]
@reginaldc could you try with QGIS nightly? There was a fix for Auth manager a couple of days ago which should resolved this issue?

**Comment by erpas** [comment]
@reginaldc can you please let us know if the issue is still valid? There was a number of changes to the plugin, including the browser model and we cannot reproduce it in any way.

**Comment by reginaldc** [comment]
Hi,

I can’t test it any more as I have switched to 3.16.6 and the plugin seems to work fine.

Regards,


Reginald Carlier
Deskundige GIS
Gemeente Ingelmunster, Oostrozebekestraat 4, 8770 Ingelmunster
T+32 51 33 74 39www.ingelmunster.be
Schrijf je in op onze nieuwsbrief!
Raadpleeg onze disclaimer 
Van: Radek Pasiok ***@***.***>
Verzonden: dinsdag 11 mei 2021 16:07
Aan: lutraconsulting/qgis-mergin-plugin ***@***.***>
CC: Reginald Carlier ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [lutraconsulting/qgis-mergin-plugin] QGIS 3.10.2 doesn't start after configuring plugin and restarting second time (#118)


@reginaldc<https://github.com/reginaldc> can you please let us know if the issue is still valid? There was a number of changes to the plugin, including the browser model and we cannot reproduce it in any way.
