### ISSUE TITLE
Bug with sync

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#119]
1- Create a project and upload it from Mergin plugin
2- Download it in Input
3- Add some features
4- Sync Input changes
5- Sync changes in QGIS

>>>> BOOM <<<<<

All your data in step 3 and 4 get wiped out by the version from QGIS.

**Comment by saberraz** [comment]
It seems that geodiff is completely broken on the plugin side. It always overwrites the survey layer on server with the desktop file

**Comment by varmar05** [comment]
see https://github.com/lutraconsulting/mergin-py-client/pull/45
