### ISSUE TITLE
Don't get the Mergin Complement

### ISSUE THREAD

**Issue by toponacho** [lutraconsulting/qgis-mergin-plugin#121]
After I've installed the Mergin complement on QGIS 3.8.3 in Wndows 10 and I've restarted QGIS the I can't find the complement on the providers list nor the process box.

Any idea what's going wrong?

Thank you

**Comment by saberraz** [comment]
Did you check in your Browser panel?
https://github.com/lutraconsulting/qgis-mergin-plugin/blob/master/docs/user-docs.md#installation

**Comment by toponacho** [comment]
That's it. I was sticking on the layer & processes panel...sorry
