### ISSUE TITLE
Can't find synchronize button from local QGIS project to Mergin server

### ISSUE THREAD

**Issue by BoswachterMarc** [lutraconsulting/qgis-mergin-plugin#122]
Hi,

I have a small issue in
QGIS version 3.4.9 Madeira with
Mergin plugin Version 20.3.1

In the user documentation I read: "With Mergin service you can synchronise your local changes back to the server. Simply, right-click on the project from the browser panel and select Synchronize"

What am I overlooking? I can't find the synchronize button in QGIS although I am right-clicking everywhere in the Mergin/browser panel... 

- Right click Mergin = configure & create new project
- Right click My projects = reload & create new project
- The project itself = download & remove from server

![Knipsel](https://user-images.githubusercontent.com/57868975/77232183-c35f5b80-6b9f-11ea-836c-d69e1c4fe13a.PNG)

Thank you,
Marc

**Comment by saberraz** [comment]
@BoswachterMarc you need to first press Download. Once there is a local copy of your project is downloaded, you can then subsequently synchronize it with the server.

**Comment by saberraz** [comment]
![Peek 2020-03-21 17-38](https://user-images.githubusercontent.com/2649047/77232787-fa7f3e00-6b9a-11ea-8555-aa4d1190b97a.gif)

**Comment by BoswachterMarc** [comment]
Aha, thanks for the explication!
That way it works ;-)

I assume there is some developer reason for first downloading the project from Mergin (after uploading...) in stead of using the local project? It's a bit weird to have twice the project on the hard drive...

But thank you anyway for the beautiful work :-)

![image](https://user-images.githubusercontent.com/57868975/77235100-4d64ef80-6bb3-11ea-9bdf-06e1a0cbb403.png)

**Comment by saberraz** [comment]
Unfortunately, it is a bug we fixed and reappeared in the latest release: https://github.com/lutraconsulting/qgis-mergin-plugin/issues/81
