### ISSUE TITLE
Sync error: upload fails with apply_changeset geodiff error

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#125]
![image001 (5)](https://user-images.githubusercontent.com/2649047/77857720-30559f80-71f7-11ea-9d35-816777a7cc97.png)

**Comment by saberraz** [comment]
1.)    I change some Records on the app ( not addin but only changeing data, no changes on geometry )

2.)    I sync on the app

3.)    I see an nev Version on the server

4.)    I try to sync on Qgis plugin --- > Project is already up to date  L

5.)    I change some data on Qgis (no changes on the project or fields )

**Comment by saberraz** [comment]
I am not able to reproduce the issue with those steps.

**Comment by wonder-sk** [comment]
This should be already fixed, please reopen if not.
