### ISSUE TITLE
No file uploaded in the first run

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#131]
To replicate the issue:
1- Open a new session in QGIS
2- Add a background layer
3- Add a survey layer
4- Save the project
5- Edit the survey layer by adding a feature
6- In the plugin, Create a new project and Initialise based on the project just created
7- It does not upload anything.

I have to close QGIS or start a new project and run Sync to get my files uploaded.

**Comment by wonder-sk** [comment]
Related PR #130 to fix incorrect error reporting on upload failure.

Today's server update made this problem disappear (removed checksum check)
