### ISSUE TITLE
Project showing up on Mergin but Input indicates "No project found"

### ISSUE THREAD

**Issue by ywjong90** [lutraconsulting/qgis-mergin-plugin#138]
Hi all, I followed through the methods on Lutra tutorial (https://www.lutraconsulting.co.uk/blog/2019/09/19/foss4guk/) and uploaded a project to Mergin using Mergin plugin on QGIS. However, when I opened Input app, the app showed "No projects found" while clicking my account showed "Used Data 5.14/100 MB" which indicated that there is something in my Mergin cloud. Does anyone know what could cause this issue? My QGIS project has .qgs file extension and is a very simple project with a basemap, a read-only shape file (my project site boundary) and an editable layer of trees (the usual .shp format), and the same sets of shape file and basemap could work fine on Qfield. Will appreciate if anyone can help troubleshooting this.

![IMG_0403](https://user-images.githubusercontent.com/66417479/83747265-f2f80d00-a692-11ea-8dd4-4550961c306a.PNG)
![IMG_0404](https://user-images.githubusercontent.com/66417479/83747275-f5f2fd80-a692-11ea-832d-f88ee0a1c61d.PNG)

**Comment by saberraz** [comment]
You need to have only **one** qgs/qgz file in your folder. If you have none or more than one, it becomes an invalid project.

In Mergin, you can see if the project is valid, if you have QGIS, Input for tags column:
![image](https://user-images.githubusercontent.com/2649047/83753363-0939a500-a662-11ea-9495-64d80c59174f.png)

Future releases of Input will warn you if you have no project or more than one. So, it will be clear to users why they cannot open the project.
