### ISSUE TITLE
Sync error: mismatch of transferred and total size

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#142]
![image](https://user-images.githubusercontent.com/2649047/85210154-85f0a280-b335-11ea-86f3-5f9923b2a9e2.png)

**Comment by wonder-sk** [comment]
Users sometimes still get this error, however:
- it is not logged in the diagnostic log, so we don't even see when/if it happened
- we don't know anything else why the sizes do not match: we should also write into the log what were the sizes of chunks and what were the actually transferred sizes - to give us a better clue what is going wrong

**Comment by BoswachterMarc** [comment]
I experienced the same problem in QGIS 3.10.4.
When I upgraded to 3.10.10 I got a python error message as mentioned in https://github.com/lutraconsulting/qgis-mergin-plugin/issues/174
![afbeelding(1)](https://user-images.githubusercontent.com/57868975/97800171-6b0f3280-1c33-11eb-80fa-149da5e3fae5.png)
![afbeelding](https://user-images.githubusercontent.com/57868975/97800175-6ea2b980-1c33-11eb-9233-fd738367b68e.png)

**Comment by BoswachterMarc** [comment]
After some trouble*, I found a way to upgrade to Qgis 3.16 on a Linux Mint 20 Ulyana machine.
But the problem of size mismatch persists...

(*) [
![MerginProblemTransferedSize](https://user-images.githubusercontent.com/57868975/97807669-5f873000-1c62-11eb-8651-d9b20192bcee.jpg)
](https://forums.linuxmint.com/viewtopic.php?f=47&t=334097)

**Comment by wonder-sk** [comment]
Fixed in https://github.com/lutraconsulting/mergin-py-client/commit/e4f9b8b83623e3d890aba8907850a0603c8de395
