### ISSUE TITLE
Connection failed, incorrect URL - with a default URL and right credentials

### ISSUE THREAD

**Issue by manad93** [lutraconsulting/qgis-mergin-plugin#143]
When I test connection with a default URL and right credentials, I always get message "Connection failed, incorrect URL". I am behind proxy, but QGIS has got right proxy settings. I have got last version of plugin and QGIS 3.10.
![clipboard01](https://user-images.githubusercontent.com/67373369/85555063-ceee7280-b625-11ea-813c-0b4e964885f3.jpg)

**Comment by saberraz** [comment]
@manad93 could you check if you have Amazon certificates under settings:

In QGIS, go to Settings > Options > Authentication > Manage Certificate > Authorities > System Root Authorities

And you should be able to see Amazon Root CA 1 , 2, 3...

**Comment by BoswachterMarc** [comment]
Having more or less the same problem I assume... see https://github.com/lutraconsulting/qgis-mergin-plugin/issues/123 and attached printscreen

![image](https://user-images.githubusercontent.com/57868975/98361795-7b0c8500-202c-11eb-878b-8cd145638172.png)

**Comment by manad93** [comment]
I am sorry for dely in response to saberraz comment. Yes it looks same as #143, so I continue with responses there.

> 
> 
> @manad93 could you check if you have Amazon certificates under settings:
> 
> In QGIS, go to Settings > Options > Authentication > Manage Certificate > Authorities > System Root Authorities
> 
> And you should be able to see Amazon Root CA 1 , 2, 3...
