### ISSUE TITLE
sync problems

### ISSUE THREAD

**Issue by marcomile** [lutraconsulting/qgis-mergin-plugin#146]
I created a new project in QGis and I inserted a geopackage which contains 4 layers. The problem is that if I add a layer to the geopackage and sync in the Input app I don't see it. Why?
Thanks so much
P.S. I synchronized on an Ipad with closed Input

**Comment by saberraz** [comment]
Do you happen to have a raster layer in your gpkg layer?

**Comment by marcomile** [comment]
H
No, I have a WMS service for orthophotos

**Comment by saberraz** [comment]
I meant if you have raster layer within your geopackage.

Have you set up the map themes correctly. See https://github.com/lutraconsulting/input/issues/789

**Comment by marcomile** [comment]
I have no raster in geopackage.
Anyway, tomorrow I'll show you my situation.
Thank you

**Comment by marcomile** [comment]
I solved it as you said ... it was the map theme that did not also include the new layer.
Thanks so much
P.S. Would it be possible to implement automatic track recording?

**Comment by saberraz** [comment]
Hi @marcomile 

Great. There is already a ticket for track recording: https://github.com/lutraconsulting/input/issues/500

Let's close this ticket and have further discussions in the relevant ones.
