### ISSUE TITLE
Changes are not shown properly with large number of files

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#148]
The window for showing Status of files does not resize appropriately, when there are large number of files to display. Best to have a scroll or another button to Show More...

**Comment by wonder-sk** [comment]
We should move away from a simple message box - we should have a tree view that would list added/modified/removed files. For the versioned files (.gpkg) we should also show summary of changes for each table as sub-items: e.g. "table1 (3 added, 1 removed)"

**Comment by wonder-sk** [comment]
This has been already addressed - there's now a proper tree view with changes.
