### ISSUE TITLE
No Write access

### ISSUE THREAD

**Issue by marcomile** [lutraconsulting/qgis-mergin-plugin#154]
I have a project shared with another person and when we try to update the data taken from two different mobile devices the input gives me the error of "No Write Access". The permissions are set for both as Owner, Write and Read.

Why?

Thanks in advance and best regards.

Marco

**Comment by saberraz** [comment]
Hi @marcomile 

Does this happen in QGIS through mergin plugin or through Input app on your mobile device?

**Comment by marcomile** [comment]
No, it only happens with the INPUT application

**Comment by mostlyAtNight** [comment]
Hi @marcomile - can you let me know what time you experienced this issue (I would like to take a look through the server logs and the time will help me track it down).

Kind regards,

Pete

**Comment by saberraz** [comment]
One thing I can suggest is to log out and into Mergin again from the app:
- Go to Projects > My Projects and click on the icon on top right
- Then select Sign out
- Sign in again

See if this helps.
![Screenshot_20200729-155949_Input](https://user-images.githubusercontent.com/2649047/88809672-4fb40780-d1ac-11ea-967e-43ba311c9c28.png)

**Comment by marcomile** [comment]
at 15 pm and even now.
I have logged out several times but nothing has changed

**Comment by marcomile** [comment]
In practice if I go to take any point on input logged differently from the owner, it tells me No Wrte access

**Comment by saberraz** [comment]
Could you confirm that the device that gives you an error is logged in with a:
1- Valid Mergin user
2- Activated user account (the follow up link after you register with Mergin to activate your account)

**Comment by marcomile** [comment]
I confirm. If I connect and download the data from mergin everything is ok but as soon as I take a point and try to synchronize it gives me the error (tried on two different devices with two different valid accounts)

**Comment by mostlyAtNight** [comment]
Hi @marcomile - which username did you connect as last when the error ocurred?

**Comment by marcomile** [comment]
susanna.galimberti or cma_prova

**Comment by mostlyAtNight** [comment]
Hi @marcomile - there's nothing indicating an issue on the server side so we will be chatting with other colleagues now who manage the Input codebase.  

Can you please let us know which version of Input you are using?  (and also on which platform, Android or IOS)?

Kind regards,

Pete

**Comment by marcomile** [comment]
Input version 0.6.4 an Android system
But I don't have the file you indicated

**Comment by marcomile** [comment]
Input version 0.6.4 on Android system
But I don't have the file you indicated

**Comment by marcomile** [comment]
Input version 0.6.4 on Android system
But I don't have the file you indicated

**Comment by marcomile** [comment]
Nothing this morning I also tried with an Ipad with the 0.6.0 version of Input but it gives me the same error ...

**Comment by saberraz** [comment]
Hi @marcomile 

Do you have the same issue if you try to make changes from QGIS desktop and sync it through the plugin using the other accounts you shared the project with?

One way of resolving the issue:
1- Back up the project on the mobile devices
2- Wipe the cache (through Settings > Apps > Input)
3- Wipe the storage (through Settings > Apps > Input)
4- Launch the app, sign in and redownload the project

**Comment by marcomile** [comment]
Synchronizing from QGis with "problematic" accounts I have no problem.
I try to do other things and then let you know.
Thanks

**Comment by saberraz** [comment]
Latest Input should have addressed this issue:
https://github.com/lutraconsulting/input/pull/966
