### ISSUE TITLE
Inconsistent Label Rendering Behavior

### ISSUE THREAD

**Issue by Saijin-Naib** [lutraconsulting/qgis-mergin-plugin#158]
Input Project Rendered on desktop:  
![image](https://user-images.githubusercontent.com/19295950/89049453-49926800-d31f-11ea-8cfb-87cac8c86fe0.png)

QGIS version | 3.14.1-Pi | QGIS code revision | de08d6b71d
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | bettereditor; CalculateGeometry; MemoryLayerSaver; Mergin; ORStools; qfieldsync; qgis-maptiler-plugin; quick_map_services; slyr; SpreadsheetLayers; zoom_level; db_manager; MetaSearch; processing

Input Project Rendered on mobile:  
![image](https://user-images.githubusercontent.com/19295950/89049850-de956100-d31f-11ea-9eea-df752b30d4af.png)

Input version: v0.6.4

The line widths and labels on Mobile are slightly thinner/smaller at similar zoom extents, leading to more difficulty reading them. Perhaps this is a DPI/scaling issue, since my desktop is 1920x1080 on a 21.5" display (102.46 DPI), and my mobile is 2280x1080 on a 6.2" display (406.91 DPI).

**Comment by saberraz** [comment]
@Saijin-Naib this is related to Input. I have opened a ticket here:
https://github.com/lutraconsulting/input/issues/997
