### ISSUE TITLE
QGIS has no attribute version

### ISSUE THREAD

**Issue by FabrizioARU** [lutraconsulting/qgis-mergin-plugin#163]
I just updated the plugin and I cannot configure it. I have the following error:
 AttributeError: type object 'Qgis' has no attribute 'version'

I am running QGIS 3.10.9 LTR on a windows computer.

The plugin was working fine before the latest release.

**Comment by wonder-sk** [comment]
Thanks for reporting - fixed in the newly released version 2020.5.2
