### ISSUE TITLE
Sync fails when path contains a single quote character

### ISSUE THREAD

**Issue by HowardEason** [lutraconsulting/qgis-mergin-plugin#164]
Thanks for getting back to me Martin Dobias:

NB: i am very much a novice in all this 3 day crash course in QGIS for University course in habitat surveying.

![image](https://user-images.githubusercontent.com/71281485/93129320-b3e14b00-f6c8-11ea-8a2b-824147e7a4d1.png)

Hopefully you can view the problem here.
Thanks
Howard.

**Comment by wonder-sk** [comment]
hi @HowardEason 

hmm interesting... could you please 1. close QGIS, 2. zip the whole folder and send the zip to me (martin.dobias@lutraconsulting.co.uk), 3. share your "phase 1" project with me on Mergin (my username is "martin") - you can add collaborators in project settings

**Comment by roya0045** [comment]
@wonder-sk Could the . in the pathname be causing this?

**Comment by wonder-sk** [comment]
Earlier today we found out it is a geodiff bug - https://github.com/lutraconsulting/geodiff/issues/74

**Comment by HowardEason** [comment]
Will I need to start the project again, or should I copy and paste the project into a different folder or will it work if I just delete the apostrophe from my name. It might perhaps be easier if I create a distinct folder for my university work?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wonder-sk** [comment]
@HowardEason it would be safest to create a new project in a new folder, copy your data files there and sync. If everything is fine, just delete the old project

**Comment by HowardEason** [comment]
Thanks, trying that now and I have created a separate folder-fingers crossed!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by HowardEason** [comment]
Hurrah it has worked!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
