### ISSUE TITLE
"Error: Invalid token type"

### ISSUE THREAD

**Issue by HugoP27** [lutraconsulting/qgis-mergin-plugin#186]
Good day, 
The plugin gives the following error when I open a blank QGIS project and try to connect to Mergin:

An error has occurred while executing Python code: 

ValueError: Invalid token type 
Traceback (most recent call last):
  File "C:/Users/hugop/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\plugin.py", line 591, in configure
    self.mc = dlg.writeSettings()
  File "C:/Users/hugop/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\configuration_dialog.py", line 88, in writeSettings
    mc = create_mergin_client()
  File "C:/Users/hugop/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\utils.py", line 116, in create_mergin_client
    return MerginClient(url, mc._auth_session['token'], username, password, get_plugin_version())
  File "C:/Users/hugop/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 51, in __init__
    token_data = decode_token_data(auth_token)
  File "C:/Users/hugop/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client.py", line 28, in decode_token_data
    raise ValueError("Invalid token type")
ValueError: Invalid token type

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.16.1-Hannover Hannover, b381a90dca 

Python Path:
C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python
C:/Users/hugop/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/hugop/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/hugop/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\hugop\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\kmltools\libs
C:\Users\hugop\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:/Users/hugop/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\hugop\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
.

**Comment by saberraz** [comment]
Hi @HugoP27 

I cannot replicate this issue. Could you try with a clean profile and Mergin plugin only?

**Comment by HugoP27** [comment]
Hi @saberraz, it only happens once in a while but when it does I just right click om the Mergin icon in the file explorer and click om 'test connection'. This sorts it out, so its not a big issue

**Comment by wonder-sk** [comment]
It seems like this happens when an existing token expires...

TODO: figure out how to replicate

**Comment by HugoP27** [comment]
Hi Guys 
I found that deleting the stored token from my user profile in QGIS sorts the problem out as @saberraz suggested

**Comment by wonder-sk** [comment]
It seems to be sorted in the recent versions of the plugin (e.g. 2021.4.1)
