### ISSUE TITLE
Problem uploading data to organisation

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#187]
I have an organisation, but when I try to create and upload data from the plugin, I get the following error message:
`Client error: The requested URL was not found on the server.`

**Comment by saberraz** [comment]
possibly related to https://github.com/lutraconsulting/mergin-py-client/issues/65

**Comment by sklencar** [comment]
Cause of the Issue:
After a transfer, a project metadata are not changed accordingly to a new namespace.

To reproduce:
1. create a project
2. download it via mergin-plugin in QGIS
3. transfer the project to organization (or another user)
4. make some changes
5A. try to sync via mergin-plugin in QGIS (the project still in "My project") 
5B. Reload shared tab and try to sync via mergin-plugin in QGIS (now the project in "Shared")

**Comment by saberraz** [comment]
![Peek 2020-12-15 14-23](https://user-images.githubusercontent.com/2649047/102227247-3ef8f980-3ee1-11eb-99e6-cfd0bd8a20b7.gif)

**Comment by saberraz** [comment]
I tried to create a project under lutraconsulting organisation and initialise it from an existing folder.

**Comment by wonder-sk** [comment]
Fixed in 1b7f79db187f
