### ISSUE TITLE
cryptic user message on session timeout

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/qgis-mergin-plugin#191]
client was using mergin plugin on windows (latest plugin, latest qgis 3.16.1) and left QGIS open during night. on morning, it was unable to synchronize with the cryptic message for user

<img width="354" alt="Screenshot 2020-12-18 at 09 18 20" src="https://user-images.githubusercontent.com/804608/102591293-1572e480-4112-11eb-9a50-1fd50341b833.png">

It would be good to instead show some windows like 

"You active session expired, you have been logged out. 
Do you want to login back?

Yes - No" 

or something like that

**Comment by wonder-sk** [comment]
My suggestion would be not to bother users with any extra windows and just renew the token if it expired. There should be already some logic in the plugin for that - but obviously it is broken.
