### ISSUE TITLE
Open a checked out project

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#217]
In a multi-user environment, if user1 checks out the project on a shared network drive, user2 can open the project as a generic QGIS project. But for user2, the project is not linked to an upstream Mergin project so, the changes cannot be synced.

It will be good to have an option in Mergin plugin to open an existing checked out project. The plugin auto-detects the Mergin project configuration and links it to the upstream project.

**Comment by wonder-sk** [comment]
Duplicate of #98 ?

As for shared network drives - we should actively try to stop users from checking out Mergin projects there, due to possible issues with GeoPackages - things can go really bad if people do that and try to do concurrent editing. Each user should have their own checkout.

**Comment by saberraz** [comment]
Indeed, it is a duplicate. Yes, I am aware of the issues with the SQLite files and shared network. This is mainly to view data.
