### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by AesculusK** [lutraconsulting/qgis-mergin-plugin#219]
I'm unable to load the survey layer for my project, so this is a fairly urgent issue:

There was an issue syncing my project, apparently because a JPG from my survey layer is duplicated? Not sure what's going on there, because all the files are present in the folder I specified, and everything looks fine.

Please let me know if I should grant someone access to the project.

Traceback (most recent call last):

  File "C:/Users/kathe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 310, in pull_timer_tick
    self.pull_conflicts = pull_project_finalize(self.job)

  File "C:/Users/kathe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 523, in pull_project_finalize
    conflicts = job.mp.apply_pull_changes(job.pull_changes, job.temp_dir)

  File "C:/Users/kathe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 466, in apply_pull_changes
    shutil.copy(src, dest)

  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)

  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))

shutil.SameFileError: 'G:\\My Drive\\Clients\\Studio3\\17970 Daves Heffernan\\17970 Daves GIS\\17970 Daves Ave\\.mergin\\fetch_v4-v11\\210413-094614.jpg' and 'G:\\My Drive\\Clients\\Studio3\\17970 Daves Heffernan\\17970 Daves GIS\\17970 Daves Ave\\210413-094614.jpg' are the same file

**Comment by saberraz** [comment]
Hi @AesculusK could you check if your storage limit?

**Comment by erpas** [comment]
Hi @AesculusK would you please send us the Diagnostic log for your project?
It is available when you right-click on your project item in the Browser tree - the last option:

![obraz](https://user-images.githubusercontent.com/3106699/114667726-1e5e7600-9d00-11eb-989e-6053aa585fc7.png)

Thanks!

**Comment by erpas** [comment]
@AesculusK you can also share the project with us, so we can track it down which commit caused the problem. Could you share it with user `saber`?

**Comment by AesculusK** [comment]
Thanks for getting back to me, Sab and Radek!

   1. I sent the diagnostic log.
   2. Sab, I am at 98% of my storage limit. I just deleted some photos, but
   my percentage used didn't change.
   3. Sab, I added you to the project as writer.
   4. For what it's worth, I did a test point right after I made the
   project, and it synced just fine.
   5. I'm also having the same issue with my project called 4 Manor. I sent
   the diagnostic log for that one and added Sab.

Best,

Katherine Naegele
She/Her
Consulting Arborist
Master of Forestry, UC Berkeley
International Society of Arboriculture Certified Arborist #WE-9658A
ISA Tree Risk Assessment Qualified
American Society of Consulting Arborists, Member
***@***.***
(408) 201-9607 (direct cell)
(408) 675-1729 (main cell)
aacarbor.com
Yelp
<https://www.yelp.com/biz/aesculus-arboricultural-consulting-mountain-view>

<http://aacarbor.com>

**Comment by erpas** [comment]
@AesculusK thank you for the logs.

While we are trying to fix the problem, if you do not have any local changes and just need to download the project from Mergin service, you could delete the local project and download it again.

Is it a network drive that you use to store your projects? Do other users have access to the files?

Let us know if you have any local changes that need to be uploaded to the service.

**Comment by wonder-sk** [comment]
We have found the bug, the fix is on the way (in the next version of the plugin).

For the time being, as suggested above, it is best to just delete your project directory (assuming you do not have any unsaved changes there) and download the project again.

**Comment by AesculusK** [comment]
Yay, that worked for both! Thank you all so much.

I've got to say, I really love this product. I used to use Mapit GIS, and
this is much slicker. Looking forward to seeing how it grows.

Katherine Naegele
She/Her
Consulting Arborist
Master of Forestry, UC Berkeley
International Society of Arboriculture Certified Arborist #WE-9658A
ISA Tree Risk Assessment Qualified
American Society of Consulting Arborists, Member
***@***.***
(408) 201-9607 (direct cell)
(408) 675-1729 (main cell)
aacarbor.com
Yelp
<https://www.yelp.com/biz/aesculus-arboricultural-consulting-mountain-view>

<http://aacarbor.com>

**Comment by wonder-sk** [comment]
Thanks for your feedback! Just to follow up, there is now a new version (2021.2) where this issue is fixed - it's recommended to update.

**Comment by AesculusK** [comment]
Awesome! Thanks, Martin :)

Katherine Naegele
She/Her
Consulting Arborist
Master of Forestry, UC Berkeley
International Society of Arboriculture Certified Arborist #WE-9658A
ISA Tree Risk Assessment Qualified
American Society of Consulting Arborists, Member
***@***.***
(408) 201-9607 (direct cell)
(408) 675-1729 (main cell)
aacarbor.com
Yelp
<https://www.yelp.com/biz/aesculus-arboricultural-consulting-mountain-view>

<http://aacarbor.com>
