### ISSUE TITLE
Plugin skips the organisation permission

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#228]
If a user belongs to an organisation as "writer", he/she cannot make changes to the project from QGIS. In Input the same user with the same permission can make changes.

**Comment by erpas** [comment]
I can't replicate it. It is working fine for me. 
I guess, the test was done for a user having organisation wide writer permissions but for the test project it was set to a reader (the default option).

**Comment by saberraz** [comment]
Hi Radek, thanks for looking into it. It could be the case. Anyways, I cannot replicate it either.

**Comment by PeterPetrik** [comment]
Workaround is to share also the project directly with user

**Comment by alexbruy** [comment]
This should be fixed now. Now we rely on the namespace permissions when checking privileges, see #355 for more details.
