### ISSUE TITLE
Couldn't load plugin 'Mergin' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by ben-neve** [lutraconsulting/qgis-mergin-plugin#230]
![Screenshot 2021-05-03 160507](https://user-images.githubusercontent.com/83570516/116845578-8a5e3b00-ac29-11eb-9b1b-52aea0dea9c7.jpg)

I have this issue when trying to install the Mergin plugin to QGIS 3.4.13. Any advice on how to solve this would be appreciated.

**Comment by wonder-sk** [comment]
Hmm it looks like there is a compatibility issue with older versions of QGIS. We will try to fix the issue, but for the time being I would recommend to upgrade your QGIS: the version 3.4 is quite old now and not supported anymore. At this point you need at least QGIS 3.8, but I would recommend upgrading to the recent long-term release QGIS 3.16.

**Comment by saberraz** [comment]
Solution: set the minimum QGIS version in meta-data to 3.10

**Comment by ben-neve** [comment]
@saberraz could you please provide a step by step on how to set the minimum version? I'm fairly new to the QGIS software.

**Comment by saberraz** [comment]
hi @ben-neve this is not a solution. We are simply going to drop support for QGIS earlier version. The only solution is to use the latest stable and supported release of QGIS: 3.16
https://qgis.org/downloads/QGIS-OSGeo4W-3.16.6-1-Setup-x86_64.exe

**Comment by ben-neve** [comment]
@saberraz thanks for clarifying. I'll get the new version.
