### ISSUE TITLE
Mergin project always opened after sync

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/qgis-mergin-plugin#236]
Sometimes you wish you sync a mergin project but NOT open it.  Nowadays, if there is a sync down or up, when the sync finishes, the mergin project is opened.  When you have another project open already which takes ages to open, this is very annoying.

**Comment by wonder-sk** [comment]
There are two issues:
1. as Pete says, project is loaded after sync even when it is not currently active
2. project is reloaded even if pull did not involve updating .qgs/.qgz project file

**Comment by erpas** [comment]
Solved in https://github.com/lutraconsulting/qgis-mergin-plugin/pull/247

**Comment by wonder-sk** [comment]
seems like the second issue is not resolved yet

**Comment by erpas** [comment]
https://github.com/lutraconsulting/qgis-mergin-plugin/pull/247/commits/d7687677645535944890cdf77954410162d30c54 should solve the second issue.
