### ISSUE TITLE
Absolute path for packaged projects

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#239]
There is an issue with the packaging process (the 2nd option from the wizard):
If the project is set to use absolute path, the resultant packaged project from the wizard process also inherits absolute path. This will result in the project with wrong layer referencing uploaded to Mergin.

We need to change the project properties to **always** use the relative path when creating and packaging the project in step 2.

**Comment by jozef-budac** [comment]
Should not be some message for the user, that we are changing the properties of the project? 
Because it can be strange, that we change some properties without notifying about it.

**Comment by wonder-sk** [comment]
@jozef-budac in the second option (package project) we rewrite the project completely (we make a copy of the original project file), so I think it is not going to be a surprise that packaged projects are forced to use relative paths...
