### ISSUE TITLE
Pull fails when local gpkg schema has been changed + doing rebase

### ISSUE THREAD

**Issue by robbie-kwt** [lutraconsulting/qgis-mergin-plugin#246]
Hi, I am attempting to synch my project through the QGIS plugin and am getting the following error message:

Failed to sync project robbie-kwt/heathfrit due to an unhandled exception.

then if i try again, i get:

Client error: Cannot patch basefile x/x/x/survey-db.gpkg! Please try syncing again.

I am also having a separate issue with a Date field not saving within the app. Updating the attribute table within QGIS saves just fine, and updating the other fields through the app is also fine, but when hitting "save" the date field reverts back to an empty field. Any thoughts?

**Comment by robbie-kwt** [comment]
Traceback (most recent call last):

  File "C:/Users/robbies/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 422, in apply_pull_changes
    self.geodiff.create_changeset(basefile, src, server_diff)

  File "C:/Users/robbies/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\main.py", line 65, in create_changeset
    return self.clib.create_changeset(base, modified, changeset)

  File "C:/Users/robbies/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 125, in create_changeset
    _parse_return_code(res, "createChangeset")

  File "C:/Users/robbies/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\deps\pygeodiff\geodifflib.py", line 41, in _parse_return_code
    raise GeoDiffLibError(msg)

Mergin.mergin.deps.pygeodiff.geodifflib.GeoDiffLibError: createChangeset


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "C:/Users/robbies/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 310, in pull_timer_tick
    self.pull_conflicts = pull_project_finalize(self.job)

  File "C:/Users/robbies/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 541, in pull_project_finalize
    conflicts = job.mp.apply_pull_changes(job.pull_changes, job.temp_dir)

  File "C:/Users/robbies/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\merginproject.py", line 438, in apply_pull_changes
    os.remove(f'{dest}-wal')

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\robbies\\Kent Wildlife Trust\\Wilder Blean - General\\03 Evidence\\Heath Frit Recording App\\survey-db.gpkg-wal'

**Comment by wonder-sk** [comment]
Hi @robbie-kwt  Thanks for the report!

Could you please:
- submit diagnostic log from the plugin - see https://help.cloudmergin.com/plugin-logs
- share the Mergin project with me - my mergin username is "martin" (reader permission would be enough) - https://help.cloudmergin.com/sharing-project
- zip the folder with your data (content of `C:\Users\robbies\Kent Wildlife Trust\Wilder Blean - General\03 Evidence\Heath Frit Recording App` folder) and send it to me for further analysis: martin dot dobias at lutraconsulting dot co dot uk

**Comment by robbie-kwt** [comment]
No worries! 

diagnostic log submitted, added you to the project and sent the email over to you.

**Comment by wonder-sk** [comment]
Thanks for the input!

To summarize the issue:
- v40 of the project is available locally
- user changes name of a column in the survey layer
- in the meanwhile, there is v41 on server from Input
- user syncs - getting errors due to failed rebase :beetle: 

It seems that in apply_pull_changes():
 1. create_changeset(base, modified) throws an exception, which is caught as failed rebase
 2. rolling back changes, it fails trying to `os.remove(f'{dest}-wal')`  --- !!! error not caught correctly, whole pull fails half-finished

Next time sync is run, it fails in a different way:
1. in pull_project_finalize() when patching basefiles the apply_diffs fails -- because the basefile was not updated correctly!
2. resorts to removal of the basefile

Then it goes back to the first error.

There are a couple of things to fix:
- avoid copying of gpkgs - rather use makeCopySqlite() from new geodiff
- maybe in project status warn user that database structure changes will cause conflicts

**Comment by wonder-sk** [comment]
> I am also having a separate issue with a Date field not saving within the app. Updating the attribute table within QGIS saves just fine, and updating the other fields through the app is also fine, but when hitting "save" the date field reverts back to an empty field. Any thoughts?

@robbie-kwt that seems to be a problem we are already aware of https://github.com/lutraconsulting/input/issues/1381 - a fix for that should be to set up the edit form widget as "Date/Time" instead of using the default "Text Edit" widget - see https://help.inputapp.io/howto/settingup_forms_datetime

**Comment by erpas** [comment]
A WIP branch:
https://github.com/lutraconsulting/mergin-py-client/tree/failing_rabase_tests

**Comment by wonder-sk** [comment]
Fixed in https://github.com/lutraconsulting/mergin-py-client/issues/30 and verified with https://github.com/lutraconsulting/mergin-py-client/pull/100
