### ISSUE TITLE
Mergin plugin doesn't see changes in layers capabilities 

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/qgis-mergin-plugin#251]
When I change layers capabilities (QGIS->Project properties->Data sources), mergin plugin doesn't see any changes so this they can't be synchronized with the server.

**Comment by wonder-sk** [comment]
Not even when you save the QGIS project?

**Comment by jozef-budac** [comment]
you are right. That was the problem :) I didn't see asterix on the project name in QGIS, so I though everything is saved.
