### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#26]
It takes a long time to upload small changes back to Mergin.

**Comment by saberraz** [comment]
Project size: 68.6 MB
Download time through plugin: 52 seconds
Direct download from Mergin website: 23 seconds
Download from within Input: 27 seconds

**Comment by saberraz** [comment]
[This PR](https://github.com/lutraconsulting/mergin-py-client/pull/11) reduces the time for plugin from 52 seconds to 26 seconds!

**Comment by varmar05** [comment]
@saberraz shall we close now?
