### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by AesculusK** [lutraconsulting/qgis-mergin-plugin#262]
Hello! This is not time sensitive, but can you please shed some light on what's going on here? Looks like some kind of duplicate file issue, but I'm not clear on what it really means or how to prevent it going forward.

When I ran the sync, all the photos appeared in the Google Drive folder for the project, but the GPKG data didn't sync. I tried downloading just the GPKG, and it had no attributes.

When I downloaded the entire project and opened it, it worked fine.

Thanks!

***

Traceback (most recent call last):

  File "C:/Users/kathe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 310, in pull_timer_tick
    self.pull_conflicts = pull_project_finalize(self.job)

  File "C:/Users/kathe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 511, in pull_project_finalize
    shutil.copy(basefile, server_file)

  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)

  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))

shutil.SameFileError: 'G:\\My Drive\\Clients\\Matheson, Bruce\\1825 Bay Laurel Drive\\1825 Bay Laurel Drive GIS\\1825 Bay Laurel\\.mergin\\ADDRESS_field_data.gpkg' and 'G:\\My Drive\\Clients\\Matheson, Bruce\\1825 Bay Laurel Drive\\1825 Bay Laurel Drive GIS\\1825 Bay Laurel\\.mergin\\fetch_v3-v7\\ADDRESS_field_data.gpkg' are the same file

**Comment by AesculusK** [comment]
Uh, I just deleted the project to free up storage - /I hope I didn't mess up your troubleshooting efforts by doing that!

**Comment by wonder-sk** [comment]
What version of the Mergin plugin are you using? If you are not using the most recent one (2021.3), please upgrade, I belive this issue has been fixed already...

**Comment by AesculusK** [comment]
Thanks, Martin! Just upgraded :)

Katherine Naegele
She/Her
Consulting Arborist
Master of Forestry, UC Berkeley
International Society of Arboriculture Certified Arborist #WE-9658A
ISA Tree Risk Assessment Qualified
American Society of Consulting Arborists, Member
***@***.***
(408) 201-9607 (direct cell)
(408) 675-1729 (main cell)
aacarbor.com
Yelp
<https://www.yelp.com/biz/aesculus-arboricultural-consulting-mountain-view>

<http://aacarbor.com>

**Comment by wonder-sk** [comment]
Cool - closing the ticket. Please feel free to reopen if you encounter the issue with the newer version of the plugin...
