### ISSUE TITLE
Problem with syncing when the speed is low

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#265]
Reported by a user:
_The plugin in QGIS is live updating into the cloud, which is with slow interconnections (like mine) which often is below 100 kbs causing trouble updating , if at all as seemingly Python breaks and blocks all_

**Comment by wonder-sk** [comment]
Do we have any diagnostic log to inspect?

**Comment by wonder-sk** [comment]
It may be worth testing upload/download of a project with limited bandwidth:
https://www.tutorialspoint.com/how-to-limit-network-bandwidth-on-linux

It seems we do not explicitly set timeouts and the default for urllib should be no timeout. It is possible there are some network errors, causing a longer upload/download to fail completely...

**Comment by jozefbudac** [comment]
I was not able to simulate it. Even with bandwidth abound 50Kb, I was able to create new project on mergin and synchronize changes. 
Interestingly, some tools as speedtest from Ookla have problem running on such a small bandwidth, but not QGIS and mergin plugin :)
