### ISSUE TITLE
QGIS UI is frozen during download/upload

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#27]

**Comment by wonder-sk** [comment]
Suggested way to implement this:
- add download_project_async() to the mergin client - it will not wait until everything is downloaded - instead it would finish immediately after submitting download tasks to the threaded pool executor
- download_project_async() should also accept a callback function that would be executed when all tasks are finished - this would be used by the plugin to hide the progress dialog
- download_project_async() would return an object that would contain all the necessary data of pending download (executor, futures etc.)
- there should be a function to cancel a pending async project download
- every "future" should have a callback assigned (see add_done_callback()) that would handle finalization of download of the particular file. In these callbacks we would also test whether the whole download is already finished
- it would be good to have the same implementation for parallel/non-parallel downloads - simply by setting the executor's max. number of threads to 1 in case of serial downloads
- it would be good to adjust download_project() implementation to be a wrapper of download_project_async() that just blocks until download is finished, so we do not have two implementations

**Comment by wonder-sk** [comment]
As soon as https://github.com/lutraconsulting/mergin-py-client/pull/44 is merged, we can update the plugin - see https://gist.github.com/wonder-sk/3150e77d3ec0912d4c4e0c8242033aea for sample GUI code for async download.

**Comment by wonder-sk** [comment]
An updated sample code snippet is here:
https://gist.github.com/wonder-sk/e9d0da7d224283c9870728df5b3faa35

(also includes handling of errors)
