### ISSUE TITLE
Sync misbehaves with trailing slash in custom mergin URL

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/qgis-mergin-plugin#285]
The plugin thinks that `http://example.com/` and `http://example.com` are two different servers and when trying to sync after the initial download, it shows an error saying "Current project was created for another Mergin server"

**Comment by varmar05** [comment]
I had the same issue, and looking a bit into that I found in .ini settings

```
localProjects\test5\lalala\server=http://localhost:5000/
server=http://localhost:5000/
```
however, they are treated differently (regarding striping trailing backslash).
