### ISSUE TITLE
Warning in project status dialog if user has modified structure of a GeoPackage

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/qgis-mergin-plugin#289]
Right now often users are not aware that changing database structure can introduce conflict files, so let's warn them in the project status dialog at the bottom, e.g. something like this:

![image](https://user-images.githubusercontent.com/193367/133262734-8c94ce0c-ff88-4631-b6b9-06dbb2c84c2e.png)

The "learn more" link would lead to the online documentation.

When user does not use "project status" dialog and only clicks "sync" button from toolbar/browser, we should still show the warning (or maybe the full status dialog?) so that this message is not lost.

**Comment by PeterPetrik** [comment]
https://merginmaps.com/docs/manage/synchronisation/
https://merginmaps.com/docs/manage/plugin-sync-project/
https://merginmaps.com/docs/manage/deploy-new-project/

**Comment by PeterPetrik** [comment]
@alexbruy this is already fixed?

**Comment by alexbruy** [comment]
Yes, it was fixed.
