### ISSUE TITLE
User not able to upload changes

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/qgis-mergin-plugin#294]
Version 2021.4.2

When user have any kind of rights as a member of the organization, he should be able to update the project (upload changes)
Right now it shows "You have no writing rights to this project"

**Comment by saberraz** [comment]
This looks like the ticket I filed earlier, but @erpas was not able to replicate: https://github.com/lutraconsulting/qgis-mergin-plugin/issues/228

**Comment by jozef-budac** [comment]
Duplicate of #256
