### ISSUE TITLE
Validation: Value relations + project level relations

### ISSUE THREAD

**Issue by tomasMizera** [lutraconsulting/qgis-mergin-plugin#296]
It would be good to have validation of value relation widgets in plugin, it could:
 1. check if referenced table exists
    - plus: check if the referenced table id is written inside layer tree, otherwise Input will not be able to find it (see #1734 and `QgisApp::resolveVectorLayerDependencies()` - it finds missing tables even when they are not present in layer tree, however the code is not in Input! ) 
 2. check if referenced table do not have duplicated values in `key` column
 3. check if `key` column has set length and if so, check that no value is longer than set length

If so, tell it to user and make some action based on it (TBD).

See https://github.com/lutraconsulting/input/issues/1297 and https://github.com/lutraconsulting/input/pull/1734

**Comment by alexbruy** [comment]
Fixed by #380.
