### ISSUE TITLE
After plugin installation, I have to restart QGIS to see Mergin in my browser panel

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#3]

**Comment by ismailsunni** [comment]
I experience this also (on Win 10, QGIS 3.10)

**Comment by PeterPetrik** [comment]
this must be fixed in QGIS code

**Comment by adibratul** [comment]
after plugin installation its not in the brower list of QGIS . 
QGIS version 3.4.6

**Comment by adibratul** [comment]
same problem after installation this plugin is not found in qgis. Did it several times. and Refresh the browser. 
QGIS version 3.4.6

**Comment by saberraz** [comment]
Do you get an error when you restart QGIS?

**Comment by adibratul** [comment]
its come after restarting QGIS. thank you

**Comment by wonder-sk** [comment]
This is fixed in QGIS 3.14 (which will be released in June) - restart will not be needed anymore.
