### ISSUE TITLE
Wrong association of a project to a mergin server

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#307]
There is a problem with the plugin that it associates a project to a wrong Mergin instance. This happens when I have multiple QGIS sessions open and I log in to https://custom-mergin.url in one session (Session1). Then go back to a QGIS session (Session0) when it is logged in to https://public-mergin.url and download a project.

When I make changes to the project in Session0 and try to sync, it wrongly associates the project with the Mergin instance https://custom-mergin.url

**Comment by saberraz** [comment]
The only reliable method to get rid of this issue is to start the QGIS with a new profile.

**Comment by varmar05** [comment]
@wonder-sk Even we use QSettings, it seems that plugin saves settings under user profile. So two different profiles can handle two different servers, which I think is the preferred way to use it.

@saberraz I tested it with 2 sessions (different profiles) opened concurrently and it works well, no restarts or anything is required.

**Comment by varmar05** [comment]
I would not go with support of multiple servers within plugin for single user (similar to other providers). It is very rare use case and it would require rewrite of browser panel. Also it would make things more complex.

**Comment by saberraz** [comment]
In that case, I am happy to park the ticket for the time being. I think the work-around to change user-profile should be a reliable method to stop the issue.

**Comment by varmar05** [comment]
Maybe we can at least add some notes to README or to docs and park it until multi-server support turns out to be necessary, which is not case now.

**Comment by saberraz** [comment]
Sounds good to me.

**Comment by saberraz** [comment]
For future reference, we **do not** need / at the end of URL. It is causing problems

**Comment by wonder-sk** [comment]
@saberraz the issue with slash at the end has been fixed now (https://github.com/lutraconsulting/qgis-mergin-plugin/issues/285) and will be released in the next release

**Comment by wonder-sk** [comment]
Closing as this has been addressed in the docs - https://github.com/MerginMaps/docs/issues/97
