### ISSUE TITLE
Validation: warn if user changes attribute table

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/qgis-mergin-plugin#315]
so if he has multiple surveyors, he will be notified it will cause conflicts and link to the help how to smoothly migrate

**Comment by PeterPetrik** [comment]
related to https://github.com/lutraconsulting/qgis-mergin-plugin/issues/316
related to https://github.com/MerginMaps/docs/issues/19

**Comment by wonder-sk** [comment]
Duplicate of #289 ?

**Comment by PeterPetrik** [comment]
it is , but the duplicate does not have "validation label"... closing this one
