### ISSUE TITLE
Check for missing layers (outside of project's directory)

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#321]
It happens that user adds a layer from somewhere else network/local drive to the project without adding it to the folder where the project is checked out.

There should be a validation to warn users about this issue.

**Comment by alexbruy** [comment]
Seems this check already implemented, see https://github.com/lutraconsulting/qgis-mergin-plugin/blob/master/Mergin/validation.py#L112
