### ISSUE TITLE
Mergin plugin crashes QGIS when you open project properties

### ISSUE THREAD

**Issue by timlinux** [lutraconsulting/qgis-mergin-plugin#336]
![image](https://user-images.githubusercontent.com/178003/152049755-32c07755-b101-4911-8e8b-3b5fc6881337.png)

QGIS version | 3.23.0-Master | QGIS code revision | 1cb926fc7c
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.10.2
GDAL/OGR version | 3.3.2
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.9.2-CAPI-1.14.3
SQLite version | 3.36.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.5
QScintilla2 version | 2.13.0
OS version | Fedora Linux 35 (Workstation Edition)
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
SRTM-Downloader | 3.1.15
SpreadsheetLayers | 2.0.1
qgis_stac | 1.0.0
project_colors_dock | 1.0.0
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

When opening the project properties I get a crash with this message:

```
20:48:34: Starting /home/timlinux/dev/cpp/QGIS-QtCreator-Build/output/bin/qgis ...
Warning 1: libXML: 0: Element 'SrcSql': This element is not expected.
Fatal: ASSERT failure in QgsProjectProperties::checkPageWidgetNameMap(): "QgisApp::projectPropertiesPagesMap() is outdated, please update. Mergin should be QWidget not Mergin", file /home/timlinux/dev/cpp/QGIS/src/app/qgsprojectproperties.cpp, line 2639
ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=688956 comm="qgis" exe="/home/timlinux/dev/cpp/QGIS-QtCreator-Build/output/bin/qgis" sig=6 res=1
20:49:11: The program has unexpectedly finished.
20:49:11: The process was ended forcefully.
20:49:11: /home/timlinux/dev/cpp/QGIS-QtCreator-Build/output/bin/qgis crashed.

```

Disabling the plugin resolves the issue.

**Comment by wonder-sk** [comment]
hi @timlinux thanks for the report. This should only affect debug builds, we will be doing another release soon. For the time being, you can apply this small change in Mergin plugin locally - https://github.com/lutraconsulting/qgis-mergin-plugin/pull/333/files
