### ISSUE TITLE
Reporting tool

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#337]
It would be good to have a feature in the plugin where user can extract reports. The tool will allow you to select two different versions of a GIS layer and generate a table summarising:
- number of features added (for all types of geometries: point, line and polygons)
- Lengths (for line and polygons)
- Area (for polygons)
- Name of the editor
- Date and time of the edit (in UTC)
- Type of edit: addition, deletion, update

**Comment by PeterPetrik** [comment]
@saberraz 

the report is just gui or you can export to CSV? 
it is 2 mergin versions, or it could work for 2 local GeoPacakges not in mergin?

**Comment by saberraz** [comment]
I would like it to be a processing tool so it can export to CSV.

It has to be for layers in a Mergin project.

**Comment by varmar05** [comment]
- client to download versions, and create diff
- CLI
- plugin to create processing tool + export to csv
