### ISSUE TITLE
Can't write to the project of the organization 

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/qgis-mergin-plugin#351]
In latest version of the plugin (2021.6), user can't upload any change with error `You have no writing rights to this project`.
It is for writer, admin and owner members rights.
It is possible to upload to the project from web interface, so I believe, it is error in plugin

https://user-images.githubusercontent.com/83582181/158535630-bb6347bd-063a-4656-ad4c-cd85be9a97d4.mp4

**Comment by jozef-budac** [comment]
duplicate of: "https://github.com/lutraconsulting/qgis-mergin-plugin/issues/228"

**Comment by varmar05** [comment]
CU-28km4we
