### ISSUE TITLE
Error when running Report on a very old version of the project

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#362]
I get the following error when I run the report tool:
![image](https://user-images.githubusercontent.com/2649047/159430000-c24efc9e-27eb-4580-9538-2b52aa59036a.png)

**Comment by tomcongreve** [comment]
Hi I've managed to run from version 400 to 944. If I take it back to 399 there's an error.

![image](https://user-images.githubusercontent.com/102225838/159686946-05778a82-176b-4418-82eb-c51fccb78adf.png)

**Comment by alexbruy** [comment]
This is an issue in the mergin client, not in the plugin. Should be fixed by lutraconsulting/mergin-py-client#131

**Comment by alexbruy** [comment]
Should be fixed in the latest mergin client code.
