### ISSUE TITLE
List the versions in the reporting tool

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#365]
It would be good if the reporting tool, autopopulate the End version in the dialogue.

A more elegant solution would be to introduce:  `mergin_project_current_version` as a variable and allow the processing tool to accept expression as input instead of numeric value.

**Comment by saberraz** [comment]
Sounds good to me @wonder-sk

**Comment by alexbruy** [comment]
I'm afraid we can't populate widget with the specific version number, it is not possible in Processing. We can implement approach suggested by @wonder-sk, show "Not set" text for the end version and in this case latest project version will be user.

To display other text we need to implement it on the QGIS side, I will be happy to make a PR for it if necessary.

**Comment by saberraz** [comment]
That sounds good to me @alexbruy to use "Not set" and the tool uses the latest version.
