### ISSUE TITLE
Problem with open shapefile when trying to sync

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#37]
This is probably (another amongst millions of) limitation of Shapefile:
1- Create a project with a Shapefile for survey layer
2- Download it through mergin plugin to a local folder. Ensure the project is open in QGIS
3- Download the project in Input
4- Make some changes in Input and sync it to mergin server
5- Try to download the changes in QGIS, while the project is open

It comes up with error that .shx (or other extensions of shapefile) exists and cannot be rewritten.

We should warn users to close the project/shapefile to be able to sync the project. The other obvious solution is not to use Shapefiles.

**Comment by varmar05** [comment]
duplicate #44
