### ISSUE TITLE
Error synching back to QGIS

### ISSUE THREAD

**Issue by robbie-kwt** [lutraconsulting/qgis-mergin-plugin#370]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\robbies\\OneDrive - Kent Wildlife Trust\\Documents\\2. Projects\\3. consultancy services\\4. mergin support\\Biodiversity Metric 3.0 QGIS template Beta test\\.mergin\\fetch_v4-v5\\Layers\\Net Gain Habitat Mapping Layers.gpkg-diff-6f995f7c-8c0c-428f-b6ef-0dd65b69081c.0'

**Comment by wonder-sk** [comment]
Could you please try moving your Mergin project directory to some place that is not also synced by OneDrive, and see if that helps? We have seen similar issues when people used Dropbox or OneDrive, their sync seems to affect Mergin plugin's sync...

**Comment by robbie-kwt** [comment]
That worked, I'll avoid one drive in future!
