### ISSUE TITLE
More informative dialog message when trying to open an empty folder

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#39]
To reproduce the pop-up window:
1- Create a blank project
2- Download it locally
3- Select to open it

this message will appear:
![image](https://user-images.githubusercontent.com/2649047/62294175-53f6f900-b462-11e9-8242-bb6aacb8d526.png)
Better to change the wording (when there is 0 project in folder):
It appears that this folder does not contain any valid QGIS project. Please transfer your projects and associated data and try again.

**Comment by wonder-sk** [comment]
Or maybe even make it just a warning? E.g.:

"It appears that this folder does not contain any valid QGIS project. Without that you won't be able to use the project in Input. Do you want to upload the folder content anyway?"

[ok] / [cancel]

**Comment by saberraz** [comment]
This message pops up when I right-click on an empty project downloaded locally and try to open it.

Also, the point you have raised is a good check to have too, when uploading data.

**Comment by varmar05** [comment]
rewording is fine, just that project is 'invalid' with none or more than one qgis projects
