### ISSUE TITLE
Since 2022.3 synching is throwing AttributeError in some projects

### ISSUE THREAD

**Issue by bastooo** [lutraconsulting/qgis-mergin-plugin#393]
We have similar (cloned) projects with a so far working value-relation. In some projects we have now problems to synch since the last update (2022.3). This is probably due to different data in the projects.

I guess it is related to #380 

The Traceback looks like this: 
```
2022-05-03T16:07:33     WARNING    Traceback (most recent call last):
              File ".../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\plugin.py", line 346, in current_project_status
              self.manager.project_status(self.mergin_proj_dir)
              File ".../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\projects_manager.py", line 164, in project_status
              validation_results = validator.run_checks()
              File ".../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\validation.py", line 97, in run_checks
              self.check_value_relation()
              File ".../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\validation.py", line 262, in check_value_relation
              idx = child_layer.fields().indexFromName(str(cfg["Key"]))
             AttributeError: 'NoneType' object has no attribute 'fields'
```
In the project one relation is declared as Associatio between a point layer (fid) and non-geo-table (with the ID of point-layer). 
The association is used in the formula layout in an own tab.

**Comment by alexbruy** [comment]
Can you share project which fails to sync with the `support` account?

**Comment by rjwillson** [comment]
this error is also happening for me for multiple projects with the plugin version 2022.3. The projects will sync properly if I remove the value relations from all fields in all layers. Because I have spawned the layers and data forms to many projects for multiple clients, all of their syncing attempts will fail if they upgrade their plugin to 2022.3. I was able to revert my plugin to a previous version to facilitate syncing for fieldwork yesterday. let me know if it helps to share a project

**Comment by rjwillson** [comment]
is it just the username "support"

**Comment by alexbruy** [comment]
@rjwillson what is the name of the project? I don't see any project with `rjwillson` namespace.

**Comment by PeterPetrik** [comment]
probably `Ecophylla-Consulting/EPC template data collection`
