### ISSUE TITLE
Change default server URL

### ISSUE THREAD

**Issue by varmar05** [lutraconsulting/qgis-mergin-plugin#414]
here https://github.com/lutraconsulting/qgis-mergin-plugin/blob/master/Mergin/utils.py#L72
to https://app.merginmaps.com/ and force use of https.

related #409

**Comment by PeterPetrik** [comment]
also change default for `@mergin_url` as https://merginmaps.com/docs/layer/plugin-variables/

**Comment by alexbruy** [comment]
Already covered by #417
