### ISSUE TITLE
Changes do not sync

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#43]
This is related to awkwardness of Geopackage again.

To reproduce, your survey layer should be gpkg
1- Download and open a project in QGIS through the plugin
2- Add a new feature to the survey layer
3- Save changes
4- Without exiting QGIS or closing the project, try to sync
5- The plugin says the sync has finished, but when you check the time-stamp of the layer on Mergin server, it is still the old one. You can confirm that changes have not been applied, by downloading the project from Mergin web interface and open it in another QGIS. The changes do not appear on the project.

If I close the project and sync, the changes will be uploaded.

**Comment by varmar05** [comment]
@saberraz resolved within this PR lutraconsulting/mergin-py-client#19 by using geodiff tool, can you please test again?

**Comment by saberraz** [comment]
I can confirm that this is now resolved.
