### ISSUE TITLE
FileExistsError: [WinError 183] Cannot create a file when that file already exists:

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#44]
When I try to sync a project (which exists locally) with server, I get this error message. Maybe it is related to this:
https://stackoverflow.com/questions/54491021/why-am-i-getting-the-error-fileexistserror-winerror-183-cannot-create-a-file

**Comment by varmar05** [comment]
with geopackage files this should not happen anymore, other survey types we will probably need to be converted

**Comment by saberraz** [comment]
A warning will be sufficient at this stage. We can then implement it correctly in #55

**Comment by rdgomt** [comment]
Hi! I've tried with geopackage and the problem persists.

**Comment by wonder-sk** [comment]
This is an issue from an old version of the plugin, I am going to close it. Please try again with the latest version, and if the problem persist, please re-open the ticket with some more details... Thanks!
