### ISSUE TITLE
The plugin still updates the geopackage based on modified time stamp

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#53]
I assumed that if no change has been made to the geopackage (https://github.com/qgis/QGIS/issues/23991) and with geodiff integration, there won't be any update of the file when syncing. But my file on server gets updated by the local copy, despite the fact that it was opened in readonly mode and no change was made to it.

**Comment by saberraz** [comment]
To reproduce the issue:
1- Open a mergin project containing Geopackage in QGIS
2- Do nothing
3- Sync the project using the plugin
4- Check the time stamp of the geopackage on the mergin website: it has been updated with the local copy.

**Comment by wonder-sk** [comment]
How about if you open that project in QGIS without syncing it using mergin plugin - will it update the time stamp or it would stay the same?

**Comment by saberraz** [comment]
Before opening the project in QGIS:
![image](https://user-images.githubusercontent.com/2649047/65584284-8dd31000-df78-11e9-90c0-d227aa47e250.png)

After opening and closing the project in QGIS:
![image](https://user-images.githubusercontent.com/2649047/65584363-b1965600-df78-11e9-96e5-0cc418882fb4.png)

**Comment by saberraz** [comment]
I have ran the geodiff on the two files and it created an empty changelog. So, the plugin should not patch the remote file, if the changelog from local file is empty.

**Comment by varmar05** [comment]
with using geodiff tool in plugin this should not be the case anymore

**Comment by saberraz** [comment]
It is no longer an issue with geodiff
