### ISSUE TITLE
Connection to Mergin server - incorrect URL 

### ISSUE THREAD

**Issue by sam-seed** [lutraconsulting/qgis-mergin-plugin#54]
When logging into Mergin within QGIS I am getting the incorrect URL message as attached photo. Have tried manually entering server details. Login details are correct and working on another device and in browser. 
<img width="499" alt="Screenshot 2019-09-28 at 20 42 39" src="https://user-images.githubusercontent.com/55928856/65821765-f8fb3b80-e231-11e9-8377-81247dc169b4.png">

**Comment by saberraz** [comment]
You need to reset your QGIS Auth password:
https://github.com/lutraconsulting/qgis-mergin-plugin/issues/48#issuecomment-531467562

**Comment by saberraz** [comment]
This has been resolved in the latest plugin (2019.5). Feel free to re-open if you still have issues.

**Comment by Cotnap** [comment]
I have a similar problem. Upgraded from QGIS 3.16 to 3.20 but problem remains. Cleared Mergin line from authentication, but still getting stuck at the login; 
<img width="540" alt="image" src="https://user-images.githubusercontent.com/62502979/128093739-3e23f4da-7cf9-4fde-98d2-21e67f4054ff.png">
