### ISSUE TITLE
Refresh the screen after sync

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#62]
When I sync the project the changes do not appear immediately. I have to refresh the layers (or zoom/pan) after the sync to see the changes. We should probably add that after each sync.

![refresh](https://user-images.githubusercontent.com/2649047/68288243-f505d900-007b-11ea-97c8-353450e8e9fe.gif)

**Comment by tastrax** [comment]
Likewise on devices.
