### ISSUE TITLE
Problem uploading large project

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#67]
When trying to create and upload a large project (2 GB), I get the following error:
![image001 (3)](https://user-images.githubusercontent.com/2649047/69004291-d9ff5880-0908-11ea-92fc-0a9c6c52b1da.png)

CC @tastrax

**Comment by varmar05** [comment]
I think we need more robust handling for sync, e.g. https://github.com/lutraconsulting/mergin-py-client/issues/6

**Comment by wonder-sk** [comment]
I think this can be closed after today's server upgrade @varmar05 ?

**Comment by varmar05** [comment]
well, we can close it, but might be worth to mention some limitations/workarounds?
