### ISSUE TITLE
Allow overwrite of directory on download

### ISSUE THREAD

**Issue by tastrax** [lutraconsulting/qgis-mergin-plugin#69]
If a new Mergin project is created from a local folder then during the download project process you really want to replace the local folder. Unfortunately you get a warning that the folder already exists. There should be an option to overwrite so you don't end up with duplicates locally.

Workflow at the moment means you need to..

- Upload from local directory
- Delete local directory
- Download from Mergin

**Comment by saberraz** [comment]
This is more like a bug to me. If we upload a directory, it should be used as the local version of project (or at least we should allow users to set that).

**Comment by saberraz** [comment]
See also: https://github.com/lutraconsulting/qgis-mergin-plugin/issues/78#issuecomment-560449192

**Comment by varmar05** [comment]
@saberraz we found a bug related to the way we used auth, no overwrite needed, do we still implement such option? I am just bit concerned having overwrite might at the end bring more issues than it solves

**Comment by saberraz** [comment]
If it resolves https://github.com/lutraconsulting/qgis-mergin-plugin/issues/81, I'd say we can close this ticket too.

**Comment by varmar05** [comment]
yes, I think it is the case.
