### ISSUE TITLE
Ability to hide projects you don't own

### ISSUE THREAD

**Issue by timlinux** [lutraconsulting/qgis-mergin-plugin#7]
<img width="289" alt="image" src="https://user-images.githubusercontent.com/178003/56496398-2dcfcd80-64f1-11e9-98d6-7379e479f81c.png">

It's going to get crowded in there (and in the Mergin website). Maybe we can use a model where you only see projects you own or have been added to as a member?

**Comment by saberraz** [comment]
How about structuring it as suggested in #1

**Comment by PeterPetrik** [comment]
please use new tab from #1 called "My projects"
