### ISSUE TITLE
Basic validation when uploading data

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#72]
Before the plugin uploads the data (during project creation), it would be good to do some basic checks and warns the user:

- The folder is empty
- There is no qgs/qgz files
- There are multiple qgs/qgz files

**Comment by wonder-sk** [comment]
Another thing to check: when using file-based layers in project, we should do some effort to check if map layers are not using data from some other directories that are not within the mergin project.

cc @tomasMizera

**Comment by saberraz** [comment]
- [ ]  Editable layers (survey layers) are in Geopackage format
- [ ] Layers are located in the same folder as the root of the project
