### ISSUE TITLE
Truncated Label

### ISSUE THREAD

**Issue by ismailsunni** [lutraconsulting/qgis-mergin-plugin#73]
![image](https://user-images.githubusercontent.com/1421861/69899924-49476480-136d-11ea-9ad3-8f32161bc183.png)

**Comment by saberraz** [comment]
@ismailsunni what is your platform? We cannot seem to be able to reproduce it on any platform/OS?

**Comment by ismailsunni** [comment]
It was Windows 10, QGIS 3.10.

Since I am now on Ubuntu 18.04, I checked and it seems has a different label (`Project Name` vs `Project`):
![image](https://user-images.githubusercontent.com/1421861/71889442-6fb5a800-3142-11ea-8eb1-213b905c9029.png)

**Comment by saberraz** [comment]
It should be:
![image](https://user-images.githubusercontent.com/2649047/71889541-42fd9280-313a-11ea-956e-3fd29f8b69e9.png)

**Comment by ismailsunni** [comment]
Hmm, it is strange then.

I tried to edit the label manually, adding a prefix. It seems, the problem occurs also in my Ubuntu 18.04
![image](https://user-images.githubusercontent.com/1421861/71889781-2dd93180-3143-11ea-9f89-9ee543de4cba.png)

I was lucky to get truncated at `Project`. :)

Perhaps my high-resolution screen is the problem? I think we have the same laptop (XPS 13).

**Comment by saberraz** [comment]
Great, thanks for the PR and confirming the issue. I am using it with an external screen all the time :)
