### ISSUE TITLE
Failed to complete Mergin project creation using QGIS plugin.

### ISSUE THREAD

**Issue by kevin-garcia** [lutraconsulting/qgis-mergin-plugin#74]
When trying to create a project from a local folder, I get the following error:

_Failed to complete Mergin project creation.
/home/steam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/deps/pygeodiff/libpygeodiff-0.7.4-python.so: wrong ELF class: ELFCLASS64
There might be a broken project at server, please use web interface to fix the issue._

**Comment by saberraz** [comment]
What operating system (version of Ubuntu) are you using?

**Comment by kevin-garcia** [comment]
I'm using LXLE 18.04, which I believe is based on Ubuntu 18.04.

**Comment by varmar05** [comment]
@kevin-garcia do you have 32 or 64 bit arch?

**Comment by saberraz** [comment]
@kevin-garcia this should be resolved in the latest plugin (version 2020.4.0), could you try and if still is having the same issue, please re-open.
