### ISSUE TITLE
Conflict

### ISSUE THREAD

**Issue by ismailsunni** [lutraconsulting/qgis-mergin-plugin#76]
After adding new feature from INPUT, I tried to check the status, there is this error message:

![image](https://user-images.githubusercontent.com/1421861/69907080-809a2d80-13ce-11ea-9028-fce678d2ed71.png)

**Comment by saberraz** [comment]
@ismailsunni the source of this _conflict.gpkg is likely to be Input (current version).

With the integration of geodiff in Input BETA, this should have been addressed. 

The Mergin plugin has geodiff integrated, so it should not create any conflict gpkg files.

**Comment by saberraz** [comment]
Hi @ismailsunni Could you try with the latest plugin?

**Comment by ismailsunni** [comment]
@saberraz tested, it works!

**Comment by saberraz** [comment]
Yayyy!!!
