### ISSUE TITLE
Allow for local times rather than GMT

### ISSUE THREAD

**Issue by tastrax** [lutraconsulting/qgis-mergin-plugin#79]
It would be good to be able to use local time rather than GMT for sync times

![IMG_2139](https://user-images.githubusercontent.com/8775395/70109107-0a801a00-169f-11ea-91c8-9e532a69807f.PNG)

**Comment by saberraz** [comment]
I have opened this ticket in Input issue tracker: https://github.com/lutraconsulting/input/issues/550
