### ISSUE TITLE
Not able to download project

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#80]
If I try to download **Explore > Pete > Photo Survey (Template)** project through Mergin plugin, I get an error:
![image](https://user-images.githubusercontent.com/2649047/70129824-5b7c1800-1677-11ea-9ed1-ef2ece2e48fa.png)

**Comment by tastrax** [comment]
likewise for TEMPLATE/Tree survey

![downloadfail](https://user-images.githubusercontent.com/8775395/70131597-aed18300-16d6-11ea-87f8-6ffd57931701.PNG)

**Comment by varmar05** [comment]
closing as per https://github.com/lutraconsulting/mergin-py-client/pull/35
