### ISSUE TITLE
Problem with syncing when adding/removing columns

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-mergin-plugin#93]
This is mainly a geodiff issue/limitation (https://github.com/lutraconsulting/geodiff/issues/16), but the plugin should handle it better.

To reproduce the error:
1- Open your project
2- Add a new column to your survey layer
3- Try to sync:
![image](https://user-images.githubusercontent.com/2649047/71804007-2ee26400-305a-11ea-9aa8-cde6a9930468.png)

**Comment by saberraz** [comment]
For the time being, it should follow the old behaviour (i.e. pre geodiff): overwrites the file on server and creates a _conflict file.

**Comment by saberraz** [comment]
![image](https://user-images.githubusercontent.com/2649047/73944352-54c58780-48ea-11ea-837d-112d7811615d.png)

**Comment by varmar05** [comment]
@saberraz I think we can close this one?
